### ISSUE TITLE
Publish this crate in a new name

### ISSUE THREAD

**Issue by NobodyXu** [cargo-bins/jobslot#3]
I'd plan to publish this crate in a new name and submit a PR to [`cc`](https://github.com/rust-lang/cc-rs) and other [dependents](https://crates.io/crates/jobserver/reverse_dependencies) to use this crate, which contains various fix and performance optimization (it can use `posix_spawn` on unix, which could use `vfork` instead of `fork`).

What name should we use?
And is there anything we need to be careful?

**Comment by passcod** [comment]
I guess there's one question here and it's, _can_ we achieve the same purpose as our fork but by depending on `jobserver` proper, as Crichton originally suggested, or not, in which case we can treat the original thread at the origin of this fork as a decent signal that a full fork is not unwelcome.

Then, naming. We could go the usual boring fork naming scheme of e.g. `cargobins-jobserver`.

We could also decide to go for different but related name. For example I note that the [general concept in make](https://www.gnu.org/software/make/manual/html_node/Job-Slots.html#Job-Slots) is called "Job Slots", so we could use `jobslots`.

Finally, we could iterate on that a bit and go for a punny name in fine software / rust tradition, perhaps `slotmachine` (leaning into "slots") or `busboy` (leaning into "server")

**Comment by NobodyXu** [comment]
> can we achieve the same purpose as our fork but by depending on jobserver proper

https://github.com/alexcrichton/jobserver-rs/issues/25 is wontfix and even valid use of `jobserver` could end up causing `process::Command::spawn` to fail.

This problem is unfixable on windows because it does not support `pre_exec` handle.

Also, `jobserver` uses `pre_exec` handle on unix, which means that `process::Command::spawn` cannot use `posix_spawn`, which might be able to use `vfork` to reduce latency and avoid memory overcommitment.

> in which case we can treat the original thread at the origin of this fork as a decent signal that a full fork is not unwelcome.

From https://github.com/alexcrichton/jobserver-rs/pull/40#issuecomment-1195689752 :

> Yes I understand it's the API itself that's causing the issue. This is so significantly different from before that I don't want to pull it into this crate. If you'd like though you could maintain a separate crate which depends on this one.

As for the naming, I think `jobslots` sounds great and make it clear what this crate is for.

**Comment by passcod** [comment]
`jobslots` it is!

**Comment by NobodyXu** [comment]
> `jobslots` it is!

I will submit a PR to change the name and version, and update other metadata.

**Comment by NobodyXu** [comment]
I've published v0.2.0!
Due to problem with the doc, I will publish v0.2.1 soon though.

And @passcod I have sent an invitation for you to join https://crates.io/crates/jobslot to reduce the bus factor.
